trigger: none

resources:
  repositories:
    - repository: eng-devops
      name: sbollap1/eng-devops
      type: github
      endpoint: sbollap1
      ref: main
      
extends:
  template: templates/simple-param.yaml@eng-devops
  parameters:
    yesNo: false
    svcconn: 'sbollap1'
    endpoint: 'eng-devops'
