resources:
  repositories:
    - repository: eng-devops
      name: sbollap1/eng-devops
      type: github
      endpoint: sbollap1  # Service connection name
      ref: main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: templates/checkout-main-repo.yaml@eng-devops
    - template: templates/checkout-eng-devops.yaml@eng-devops
