# deploy
pr: none

trigger: none

resources:
    repositories:
        - repository: eng-devops
          name: sbollap1/eng-devops
          type: github
          endpoint: sbollap1
          ref: main
        - repository: eng-scim
          name: sbollap1/eng-scim
          type: github
          endpoint: sbollap1
          ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: MyDeploy
  jobs: 
  - job: MyTestJob
    steps:
       - script: cd $(Build.SourcesDirectory)/ ; ls -ltr ;
         displayName: MyTestJob Step one
       - checkout: eng-devops
       - template: templates/steps.yaml@eng-devops
       - script: cd $(Build.SourcesDirectory)/ ; ls -ltr ;
         displayName: MyTestJob Step one
