resources:
  repositories:
    - repository: eng-devops
      name: sbollap1/eng-devops
      type: github
      endpoint: sbollap1
      ref: main

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: templates/checkout-main-repo.yaml@eng-devops  # Checkout main repo
    - template: templates/checkout-eng-devops.yaml@eng-devops  # Checkout eng-devops repo
      parameters:
        serviceConnection: 'sbollap1'
    - template: templates/step1.yaml@eng-devops
    - template: templates/step2.yaml@eng-devops