# deploy
pr: none

trigger: none

resources:
    repositories:
        - repository: eng-devops
          name: sbollap1/eng-devops
          type: github
          endpoint: sbollap1
          ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Checkout
  jobs: 
  - job: checkoutjob
    steps:
       - checkout: self
- template: templates/mytemplate2.yaml@eng-devops
